SELECT t1.AMOUNT_VALUE, t1.COB_DATE, t1.PERIODICITY_CODE, t1.MCR_RATE_CODE, t1.EXCHANGE_RATE_TYPE, t1.FROM_CURRENCY_CODE, t1.TO_CURRENCY_CODE, t1.EXCHANGE_RATE, 
  t1.SOURCE_SYSTEM_CODE, <put other columns here>, t2.EXCHANGE_RATE AS J
FROM Temp1 AS t1
LEFT JOIN (
    SELECT AMOUNT_VALUE, COB_DATE, PERIODICITY_CODE, MCR_RATE_CODE, EXCHANGE_RATE_TYPE, EXCHANGE_RATE, SOURCE_SYSTEM_CODE
    FROM Temp1
    WHERE FROM_CURRENCY_CODE = 'CHF' AND TO_CURRENCY_CODE = 'USD'
) AS t2
ON t1.AMOUNT_VALUE = t2.AMOUNT_VALUE AND t1.COB_DATE = t2.COB_DATE 
AND t1.PERIODICITY_CODE = t2.PERIODICITY_CODE AND t1.MCR_RATE_CODE = t2.MCR_RATE_CODE AND  t1.EXCHANGE_RATE_TYPE = t2.EXCHANGE_RATE_TYPE AND 
  t1.SOURCE_SYSTEM_CODE = t2.SOURCE_SYSTEM_CODE;
